version: "3.7"

networks:
  becomex_challenge:
    driver: bridge

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    networks:
      - becomex_challenge

  api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://localhost:5000/
    ports:
      - 5000:5000
    networks:
      - becomex_challenge

  ui:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 4200:4200
    networks:
      - becomex_challenge